Dev
frontend-park-mail-ru/2018_2_42 pull request #5
Opened 2018-10-03 15:51 UTC by DikarevAndrey

2018-10-09 15:19 UTC, reo7sp requested changes

2018-10-09 15:19 UTC, reo7sp commented on nginx/nginx.conf
> +			proxy_pass http://localhost:8080 ;
Я как понимаю вы подключаете снаружи контейнер с бекендом. А тестили работает ли так? Емнип, нужно писать не `localhost`, а название контейнера в докерной сети (оно задается какое хотите https://docs.docker.com/network/bridge/#connect-a-container-to-a-user-defined-bridge). 

То есть, если назовем контейнер с беком как `api`, то тут стоит будет писать `proxy_pass 
 http://api:8080;`.

2018-10-09 15:19 UTC, reo7sp commented on public/js/components/Form/SignInForm.mjs
> +            action: "/api/v1/session ",
У вас тут пробел внутри строки. Так работает или не тестили?)

2018-10-09 15:19 UTC, reo7sp commented on public/js/components/Form/SignInForm.mjs
> +        this.form = this._el.getElementsByClassName('form__sign_in')[0];
<s>Не, не стоит искать элементы по классам и выбирать первый. Стоит использовать для этого id.

Прост классы — это больше для стилей и больше для добавления какой-то общей функциональности (например, всем '.button' какую-то хитрую анимашку на js закодить). А конкретную логику стоит по id вешать.
</s>

Друг-фронтендер сказал, что не надо id юзать, как я говорю, разве что стоит доставать элемент по красивее: `this._el.querySelector('.form__sign_in');`

2018-10-09 15:19 UTC, reo7sp commented on public/js/components/Button/Button.tmpl.js
> +;(function(){var x=Function('return this')();if(!x.fest)x.fest={};x.fest['js/components/Button/Button.tmpl']=function (__fest_context){"use strict";var __fest_self=this,__fest_buf="",__fest_chunks=[]
Ой, ребят, а давайте выпилим эти *.tmpl.js, они все равно автоматически генерятся на старте приложения, а в гит коммитах мешаются. В .gitignore добавьте их, и потом удалите через `git rm --cached`.

2018-10-09 15:19 UTC, reo7sp commented on public/js/components/Form/SignInForm.mjs
> +        this.form.addEventListener('submit', function(event) {
Давайте использовать стрелочные функции, как принято в _2к18_ https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Functions/Arrow_functions. Тогда и писать `.bind(this)` не надо будет

2018-10-09 15:19 UTC, reo7sp commented on public/js/components/Form/SignInForm.mjs
> +        setTimeout(function () {
И тут тоже и потом тоже можно юзать стрелочные функции для красоты

2018-10-09 15:19 UTC, reo7sp commented on public/js/components/Form/SignInForm.mjs
> +                    localStorage.setItem("login", that._login);
Лучше заменить приколы с that = this на стрелочные функции

2018-10-09 15:19 UTC, reo7sp commented on public/js/components/Form/SignInForm.mjs
> +        this._login = this.form["Login"].value;
Я чтот не увидел использование полей `this._login` и `this._password` вне этой функции. Может на обычные переменные заменить?

2018-10-09 15:31 UTC, DikarevAndrey commented on public/js/components/Button/Button.tmpl.js
> +;(function(){var x=Function('return this')();if(!x.fest)x.fest={};x.fest['js/components/Button/Button.tmpl']=function (__fest_context){"use strict";var __fest_self=this,__fest_buf="",__fest_chunks=[]
Так они же на деплойном сервере нужны, как их убрать из гита? На сервер заливается же уже полностью собранная версия, не?

2018-10-10 12:08 UTC, reo7sp commented on public/js/components/Button/Button.tmpl.js
> +;(function(){var x=Function('return this')();if(!x.fest)x.fest={};x.fest['js/components/Button/Button.tmpl']=function (__fest_context){"use strict";var __fest_self=this,__fest_buf="",__fest_chunks=[]
А, а now не умеет вызывать какие-то команды при старте? Если не может, то, оке, оставьте. Прост вы тут докеры мутите, можно сделать командочку типа `npm run build`, которая соберет все, и запускать ее в докерфайле

2018-10-10 13:53 UTC, Unanoc commented on nginx/nginx.conf
> +			proxy_pass http://localhost:8080 ;
Макс это потом поправит, говорит там свои нюансы, надо посидеть)

2018-10-10 15:25 UTC, closed without merging